name: "version macos matrix build all CI workflow"


on:
  push:
    branches: [ test ]
  schedule:
      # https://crontab.guru/examples.html #every friday at midnight  
      - cron:  '0 0 * * FRI' 
jobs:

  ubuntu-latest-2110-job:
    name: "docker  ansible clearlinux"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
        #  - golang
        #  - python
         #windows cluster
         - base                 
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch   
    - name: "run docker-osx monterey"
      run: |
        dir=$(pwd)
        cd $dir/dockerfiles/macos/base
        #Monterey
        docker build -t docker-osx --build-arg SHORTNAME=monterey  .
        docker image ls         
    - name: "run docker-osx catalina"
      run: |
        dir=$(pwd)
        cd $dir/dockerfiles/macos/base
        #Catalina
        docker build -t docker-osx/catalina . 
        # docker build -t docker-osx/catalina --build-arg VERSION=10.15.5 --build-arg SIZE=200G .
        docker image ls  
    - name: "run docker-osx big-sur"
      run: |
        dir=$(pwd)
        cd $dir/dockerfiles/macos/base
        #Big Sur
        docker build -t docker-osx --build-arg SHORTNAME=big-sur .
        docker image ls                            
